In [1]:
import tensorflow as tf

In [2]:
layer = tf.keras.layers.Dense(100)
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))


In [3]:
layer(tf.zeros([10, 5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [4]:
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.02504957,  0.31316555,  0.25598943, -0.29580352,  0.40977222,
         -0.01587898, -0.4272775 , -0.02527529, -0.1063332 , -0.54848576],
        [ 0.00183225,  0.3725322 , -0.5736945 , -0.1623019 ,  0.53005356,
          0.32091248,  0.24036336,  0.5365351 ,  0.50276476,  0.44644493],
        [ 0.45659572,  0.01288265,  0.56845635,  0.52243394,  0.08189827,
          0.44678253,  0.00106639,  0.24607718,  0.61886126, -0.00960737],
        [-0.5658538 ,  0.43991834, -0.03462362, -0.31683606,  0.44828814,
          0.08727694, -0.56542116, -0.2808534 ,  0.20621157, -0.40483946],
        [ 0.01973003, -0.2953979 ,  0.45602947, -0.51577187,  0.3678084 ,
         -0.3165622 , -0.13343573,  0.234613  , -0.52645046,  0.14998287]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [5]:
layer.trainable_variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.02504957,  0.31316555,  0.25598943, -0.29580352,  0.40977222,
         -0.01587898, -0.4272775 , -0.02527529, -0.1063332 , -0.54848576],
        [ 0.00183225,  0.3725322 , -0.5736945 , -0.1623019 ,  0.53005356,
          0.32091248,  0.24036336,  0.5365351 ,  0.50276476,  0.44644493],
        [ 0.45659572,  0.01288265,  0.56845635,  0.52243394,  0.08189827,
          0.44678253,  0.00106639,  0.24607718,  0.61886126, -0.00960737],
        [-0.5658538 ,  0.43991834, -0.03462362, -0.31683606,  0.44828814,
          0.08727694, -0.56542116, -0.2808534 ,  0.20621157, -0.40483946],
        [ 0.01973003, -0.2953979 ,  0.45602947, -0.51577187,  0.3678084 ,
         -0.3165622 , -0.13343573,  0.234613  , -0.52645046,  0.14998287]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [6]:
layer.weights

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.02504957,  0.31316555,  0.25598943, -0.29580352,  0.40977222,
         -0.01587898, -0.4272775 , -0.02527529, -0.1063332 , -0.54848576],
        [ 0.00183225,  0.3725322 , -0.5736945 , -0.1623019 ,  0.53005356,
          0.32091248,  0.24036336,  0.5365351 ,  0.50276476,  0.44644493],
        [ 0.45659572,  0.01288265,  0.56845635,  0.52243394,  0.08189827,
          0.44678253,  0.00106639,  0.24607718,  0.61886126, -0.00960737],
        [-0.5658538 ,  0.43991834, -0.03462362, -0.31683606,  0.44828814,
          0.08727694, -0.56542116, -0.2808534 ,  0.20621157, -0.40483946],
        [ 0.01973003, -0.2953979 ,  0.45602947, -0.51577187,  0.3678084 ,
         -0.3165622 , -0.13343573,  0.234613  , -0.52645046,  0.14998287]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [7]:
layer.kernel

<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.02504957,  0.31316555,  0.25598943, -0.29580352,  0.40977222,
        -0.01587898, -0.4272775 , -0.02527529, -0.1063332 , -0.54848576],
       [ 0.00183225,  0.3725322 , -0.5736945 , -0.1623019 ,  0.53005356,
         0.32091248,  0.24036336,  0.5365351 ,  0.50276476,  0.44644493],
       [ 0.45659572,  0.01288265,  0.56845635,  0.52243394,  0.08189827,
         0.44678253,  0.00106639,  0.24607718,  0.61886126, -0.00960737],
       [-0.5658538 ,  0.43991834, -0.03462362, -0.31683606,  0.44828814,
         0.08727694, -0.56542116, -0.2808534 ,  0.20621157, -0.40483946],
       [ 0.01973003, -0.2953979 ,  0.45602947, -0.51577187,  0.3678084 ,
        -0.3165622 , -0.13343573,  0.234613  , -0.52645046,  0.14998287]],
      dtype=float32)>

In [8]:
layer.bias

<tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [9]:
class CustomDense(tf.keras.layers.Layer):
    
    def __init__(self, output_units):
        super(CustomDense, self).__init__()
        self.output_units = output_units
        
    def build(self, input_shape):
        self.kernel = self.add_weight(name="kernel", shape=[int(input_shape[-1]), self.output_units])
        # int(input_shape[-1]), self.output_units] since matrix multiplication.
        
    def call(self, input):
        return tf.matmul(input, self.kernel)     

In [10]:
layer = CustomDense(10)

In [11]:
_ = layer(tf.zeros([10, 5])) # Calling the layer `.builds` it.
print([var.name for var in layer.trainable_variables])


['custom_dense/kernel:0']


In [15]:
#RESNET

class ResidualBlock(tf.keras.models.Model):
    
    def __init__(self, filters, kernel_size):
        super(ResidualBlock, self).__init__()
        self.filter1, self.filter2, self.filter3 = filters
        
        self.conv1 = tf.keras.layers.Conv2D(self.filter1, kernel_size, name="Conv1")
        self.batch_norm1 = tf.keras.layers.BatchNormalization(name="BatchNorm1")
        
        self.conv2 = tf.keras.layers.Conv2D(self.filter2, kernel_size, name="Conv2")
        self.batch_norm2 = tf.keras.layers.BatchNormalization(name="BatchNorm2")
        
        self.conv3 = tf.keras.layers.Conv2D(self.filter3, kernel_size, name="Conv3")
        self.batch_norm3 = tf.keras.layers.BatchNormalization(name="BatchNorm3")
        
    def call(self, input_tensor, training=False):
        x = self.conv1(input_tensor)
        x = self.batch_norm1(x, training=training)
        x = tf.nn.relu(x)

        x = self.conv2(x)
        x = self.batch_norm2(x, training=training)
        x = tf.nn.relu(x)

        x = self.conv3(x)
        x = self.batch_norm3(x, training=training)
        x = tf.nn.relu(x)

        x += input_tensor
        return tf.nn.relu(x)

In [16]:
resnet = ResidualBlock([1, 2, 3], 1)

In [17]:
_ = resnet(tf.zeros([1, 2, 3, 3])) 

In [19]:
resnet.layers


In [21]:
len(resnet.variables)


18

In [22]:
resnet.summary()


Model: "residual_block"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Conv1 (Conv2D)               multiple                  4         
_________________________________________________________________
BatchNorm1 (BatchNormalizati multiple                  4         
_________________________________________________________________
Conv2 (Conv2D)               multiple                  4         
_________________________________________________________________
BatchNorm2 (BatchNormalizati multiple                  8         
_________________________________________________________________
Conv3 (Conv2D)               multiple                  9         
_________________________________________________________________
BatchNorm3 (BatchNormalizati multiple                  12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
_______________________________________________________